"""
test_first_model.py
-------------------
Generates N synthetic sessions from your real sensor files, then runs
the full train → evaluate pipeline so you can confirm every piece works
before collecting real data.

What it does
------------
  1. Copies your real .bcrx and *leap*.csv into N session directories,
     each with a different participant ID and a randomised (but structured)
     embodiment score.
  2. Runs test_pipeline.py logic on each to confirm loading works.
  3. Calls build_training_dataset() to produce X, y.
  4. Trains a Ridge model with LOSO-CV.
  5. Saves the model to artifacts/ and prints a result summary.

The scores are fake — the model output is meaningless — but every line
of code from parser → feature matrix → LOSO-CV → saved .pkl will have
been exercised exactly as it will be in production.

Usage (from repo root)
----------------------
    python embodiment_model/scripts/test_first_model.py \
        --bcrx        data/raw/embodiment/P01_test_trial001/bioradio1.bcrx \
        --leap        data/raw/embodiment/P01_test_trial001/leap_pinch1.csv \
        --output-dir  data/raw/embodiment/ \
        --n-sessions  6 \
        --model-out   artifacts/embodiment-model/

    # Run with fewer sessions (minimum 2):
    python embodiment_model/scripts/test_first_model.py \
        --bcrx  data/raw/embodiment/P01_test_trial001/bioradio1.bcrx \
        --leap  data/raw/embodiment/P01_test_trial001/leap_pinch1.csv \
        --n-sessions 2
"""

from __future__ import annotations

import argparse
import json
import logging
import shutil
import sys
from pathlib import Path

import numpy as np

# ── path resolution ────────────────────────────────────────────────────────
_script_dir = Path(__file__).resolve().parent
_src_root   = _script_dir.parent / "src"
_repo_root  = _script_dir.parent.parent
sys.path.insert(0, str(_repo_root))
sys.path.insert(0, str(_src_root))

from data.data_loader    import load_sessions
from data.dataset_builder import build_training_dataset
from models.trainer      import train_embodiment_model, save_model

logger = logging.getLogger(__name__)

OK   = "✓"
WARN = "⚠"
FAIL = "✗"


# ---------------------------------------------------------------------------
# Dummy session factory
# ---------------------------------------------------------------------------

def create_dummy_sessions(
    bcrx_path: Path,
    leap_path: Path,
    output_dir: Path,
    n_sessions: int = 6,
    seed: int = 42,
) -> list[Path]:
    """
    Create N session directories under output_dir using the real sensor files.

    Participant IDs cycle P01..P0N so LOSO-CV has someone to hold out.
    Embodiment scores are spread across [20, 85] with light random noise
    so the model has a real gradient to fit.

    Returns list of created session directories.
    """
    rng = np.random.default_rng(seed)
    conditions = ["control", "vibrotactile", "visual"]
    base_scores = np.linspace(25, 80, n_sessions)
    session_dirs: list[Path] = []

    print(f"\nCreating {n_sessions} dummy session(s) in {output_dir}")
    print(f"  Source .bcrx:    {bcrx_path.name}")
    print(f"  Source leap CSV: {leap_path.name}")

    for i in range(n_sessions):
        pid       = f"P{(i % 3) + 1:02d}"          # P01, P02, P03, P01, P02, P03 ...
        condition = conditions[i % len(conditions)]
        trial_num = (i // 3) + 1
        score     = float(np.clip(base_scores[i] + rng.normal(0, 5), 0, 100))

        # Use the BioRadio recording start time, offset by i*10s per session
        from datetime import datetime, timezone, timedelta
        t0    = datetime(2026, 1, 27, 20, 33, 16, tzinfo=timezone.utc) + timedelta(seconds=i * 60)
        t_end = t0 + timedelta(seconds=9)

        session_name = f"{pid}_{condition}_trial{trial_num:03d}"
        sdir = output_dir / session_name
        sdir.mkdir(parents=True, exist_ok=True)

        # Copy sensor files
        shutil.copy(bcrx_path, sdir / bcrx_path.name)
        shutil.copy(leap_path,  sdir / leap_path.name)

        # Write labels.json with varied VEQ scores
        labels = {
            "participant_id":  pid,
            "condition":       condition,
            "trial_number":    trial_num,
            "embodiment_score": round(score, 1),
            "veq_ownership":   int(rng.integers(2, 7)),
            "veq_agency":      int(rng.integers(2, 7)),
            "veq_location":    int(rng.integers(2, 7)),
            "session_start":   t0.isoformat(),
            "session_end":     t_end.isoformat(),
            "notes":           "DUMMY — generated by test_first_model.py",
        }
        with open(sdir / "labels.json", "w") as f:
            json.dump(labels, f, indent=2)

        print(f"  {OK}  {session_name}  score={score:.1f}")
        session_dirs.append(sdir)

    return session_dirs


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(args):
    print("\n" + "=" * 65)
    print("  FIRST MODEL PIPELINE TEST")
    print("=" * 65)

    bcrx_path = Path(args.bcrx)
    leap_path = Path(args.leap)

    for p, name in [(bcrx_path, "--bcrx"), (leap_path, "--leap")]:
        if not p.exists():
            print(f"\n{FAIL}  {name} file not found: {p}")
            print("   Run from repo root and provide paths to your real sensor files.")
            sys.exit(1)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # ── 1. Create dummy sessions ───────────────────────────────────────
    session_dirs = create_dummy_sessions(
        bcrx_path, leap_path,
        output_dir=output_dir,
        n_sessions=args.n_sessions,
    )

    # ── 2. Load all sessions ───────────────────────────────────────────
    print(f"\n{'─'*65}")
    print("Loading sessions...")
    sessions = load_sessions(output_dir)

    # Filter to only the dummy ones we just created (ignore any pre-existing)
    dummy_names = {d.name for d in session_dirs}
    sessions = [s for s in sessions if s.session_dir.name in dummy_names]

    print(f"  {OK}  {len(sessions)} session(s) loaded")

    if len(sessions) < 2:
        print(f"\n{FAIL}  Need ≥ 2 sessions for LOSO-CV. Got {len(sessions)}.")
        sys.exit(1)

    # ── 3. Build feature matrix ────────────────────────────────────────
    print(f"\n{'─'*65}")
    print("Building feature matrix...")
    X, y = build_training_dataset(sessions)

    participant_ids = [s.participant_id for s in sessions if s.session_id in X.index]
    feature_names   = list(X.columns)

    print(f"  {OK}  Shape:  {X.shape[0]} sessions × {X.shape[1]} features")
    print(f"  {OK}  Score range: [{y.min():.1f}, {y.max():.1f}]")
    print(f"  Features: {feature_names}")

    nan_pct = X.isna().mean()
    nan_cols = nan_pct[nan_pct > 0]
    if not nan_cols.empty:
        print(f"\n  {WARN}  NaN columns (expected without real watch data):")
        for col, pct in nan_cols.items():
            print(f"       {col}: {pct:.0%}")

    # ── 4. Train first model ───────────────────────────────────────────
    print(f"\n{'─'*65}")
    print("Training Ridge model (LOSO-CV)...")
    print("NOTE: scores are fake — R² will be near 0 or negative. That's expected.")
    print("      Goal is to confirm every pipeline stage runs without error.\n")

    model, cv_results = train_embodiment_model(
        X.values, y.values, participant_ids,
        model_type="ridge",
        feature_selection=False,    # skip Lasso selection — too few samples
        feature_names=feature_names,
    )

    # ── 5. Save model ──────────────────────────────────────────────────
    model_out = Path(args.model_out)
    model_out.mkdir(parents=True, exist_ok=True)
    model_path = model_out / "first_model_TEST.pkl"

    save_model(model, cv_results, model_path, metadata={
        "note":           "DUMMY MODEL — fake scores, for pipeline testing only",
        "n_sessions":     len(sessions),
        "n_participants": len(set(participant_ids)),
        "features":       feature_names,
    })

    # ── 6. Summary ─────────────────────────────────────────────────────
    print(f"\n{'='*65}")
    print("  PIPELINE TEST COMPLETE")
    print(f"{'='*65}")
    print(f"  {OK}  Sessions created:  {len(sessions)}")
    print(f"  {OK}  Features built:    {X.shape[1]} columns")
    print(f"  {OK}  LOSO-CV ran:       R²={cv_results['r2']:.3f}  MAE={cv_results['mae']:.1f}")
    print(f"  {OK}  Model saved:       {model_path}")
    print()

    if cv_results['r2'] < 0:
        print(f"  {WARN}  R² is negative — this is EXPECTED with fake scores and")
        print( "       only a few sessions. Real data will fix this.")
    else:
        print(f"  {WARN}  R² looks surprisingly OK — still fake data, don't read into it.")

    # Clean up dummy dirs if requested
    if args.cleanup:
        print(f"  Cleaning up {len(session_dirs)} dummy session(s)...")
        for d in session_dirs:
            shutil.rmtree(d)
        print(f"  {OK}  Removed.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate dummy sessions and test the full training pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--bcrx",       type=str, required=True,
                        help="Path to a real .bcrx file")
    parser.add_argument("--leap",       type=str, required=True,
                        help="Path to a real *leap*.csv file")
    parser.add_argument("--output-dir", type=str,
                        default="data/raw/embodiment/",
                        help="Where to create dummy session dirs (default: data/raw/embodiment/)")
    parser.add_argument("--n-sessions", type=int, default=6,
                        help="Number of dummy sessions to create (min 2, default 6)")
    parser.add_argument("--model-out",  type=str,
                        default="artifacts/embodiment-model/",
                        help="Where to save the test model .pkl")
    parser.add_argument("--cleanup",    action="store_true",
                        help="Delete the dummy session dirs after the test")
    parser.add_argument("--log-level",  default="WARNING",
                        choices=["DEBUG", "INFO", "WARNING", "ERROR"])
    args = parser.parse_args()

    if args.n_sessions < 2:
        print("--n-sessions must be ≥ 2")
        sys.exit(1)

    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(levelname)s [%(name)s]: %(message)s",
    )
    main(args)